### PR TITLE
Add option to compute a field using a HMAC or digest

### PR DESCRIPTION
**Pull request by ato**
Possible implementation of #79.

### TODO

* [x] Range header support - probably just need a $range template variable that evaluates to the string `"bytes=" + offset + "-" + (offset + length - 1)` which can correspond to `$http_range` in nginx
* [ ] Secret keys shouldn't appear in command-line parameters, do something about this
* [ ] Maybe convenience options for configuring the S3 template automatically
* [ ] Test S3
* [ ] Check we have the needed pieces support AWS V4 signing (it looks like that might be needed for the range header?)
* [ ] Figure out an example for Apache

### Example query

```
$ curl 'http://localhost:8080/foo?url=http://example.com&fl=original,timestamp,warcurl,range'
http://example.com/ 20140103030321 http://nginx-server/warcs/example.warc.gz?expires=1583828836&md5=yPf8VITsUZkldGIt24V3zg bytes=333-1375
http://example.com/ 20140103030341 http://nginx-server/warcs/example.warc.gz?expires=1583828836&md5=iZdrAQ0hdmxPTMuWiSoVUg bytes=1864-2416
```

### nginx example

Example nginx configuration:

```nginx
location /warcs/ {
   secure_link $arg_md5,$arg_expires;
   secure_link_md5 "$secure_link_expires|$uri|$http_range|secret";
   if ($secure_link != "1") { return 403; }
   ...
}
```

Corresponding OutbackCDX option:

```
--hmac-field warcurl md5 '$expires|/warcs/$filename|$range|$secret_key'
     'http://nginx-server/warcs/$filename?expires=$expires&md5=$hmac_base64_url'
     secret 3600
```

### S3 example (yet to be tested)

Replace `s3-access-key-id`, `s3-secret-key` and `bucket` with appropriate values:

```
--hmac-field warcurl Hmacsha1 'GET$LF$LF$LF$expires$LF/bucket/$filename'
     'https://s3.amazonaws.com/bucket/$filename?AWSAccessKeyId=s3-access-key-id&Expires=$expires&Signature=$hmac_base64_pct'
     s3-secret-key 3600 
```

### CODE REVIEW

**Comment by ikreymer** [comment]
Great! Given that `secure_link_md5` can be customized, should be easy to include the range header in the verification!

Also, found this module:
https://github.com/nginx-modules/ngx_http_hmac_secure_link_module

which provides alternative hashing functions so not limited to md5

**Comment by ato** [comment]
Yep, I had the ngx_http_hmac_secure_link_module in mind too as a more secure alternative to the vanilla md5 support. I included an example for it in the README although I haven't compiled the module to test it actually works yet.

A few things we could try to be compatible with:

* apache [ap_expr](https://httpd.apache.org/docs/2.4/expr.html) (stock)
  * Apache's expression language has sha1 and md5 functions which look like they could be used in a [Require expr](https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html#requiredirectives) or RewriteCond directive to implement a compatible scheme ([one example](https://makandracards.com/makandra/70814-self-expiring-urls-with-apache))
  * Expressions can access HTTP headers so it should be possible to cover Range

* lighttpd [mod_secdownload](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModSecDownload) (stock)
  * needs a hex-encoded unix timestamp so we'd need to add a variable for that.
  * doesn't support byte ranges
* apache [mod_auth_token](http://code.google.com/p/mod-auth-token/) (community)
  * clone of lighttpd's mod_secdownload
* Google Cloud Storage [signed urls](https://cloud.google.com/storage/docs/access-control/signed-urls)
   * looks very similar to S3
* Azure [shared access signature](https://docs.microsoft.com/en-us/rest/api/storageservices/service-sas-examples)
  * no obvious byte range support

**Comment by ikreymer** [comment]
Created this repo to help testing with the nginx 
https://github.com/nginx-modules/ngx_http_hmac_secure_link_module module.

https://github.com/ikreymer/client-replay-wayback

Appears to be working with full WARCs, but still need the `$range` template to fully be testable per record.

Also, perhaps the `range` should also be supported as a response field name, eg:
```
curl 'http://localhost:8080/foo?url=http://example.com&fl=original,timestamp,range,warcurl'
```

and then the client can just take the range string and stick it in the Range: header?

**Comment by ato** [comment]
> perhaps the range should also be supported as a response field name

Good idea. Implemented and the nginx example in this PR updated.

Note: I also changed the base64 encoding to without padding as that was necessary for compatibility with lighttpd (and hey it makes the URLs slightly shorter). nginx secure link md5 seems to be happy with or without padding, not sure about the other modules yet, if there are any that require padding I'll add both variants as variables.

**Pull request merged**
